blog/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup_view, name="signup"),
    path('login/', views.login_view, name="login"),
    path('logout/', views.logout_view, name="logout"),
]

blog/articles/urls.py
from django.urls import path, include
from . import views

app_name = 'articles'

urlpatterns = [
    path('', views.article_list, name='home'),
    path('articles/', views.article_list, name='article_list'),
    path('articles/create/', views.article_create, name='article_create'),
    path('articles/<slug:slug>/', views.article_detail, name='article_detail'),
    path('', include('django.contrib.auth.urls')),
]

blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('articles.urls', namespace='articles')),
    path('accounts/', include('accounts.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/accounts/models.py
from django.db import models

# Create your models here.

blog/articles/models.py
from django.db import models
from django.utils import timezone
from django.utils.text import slugify
from django.contrib.auth.models import User

class Article(models.Model):
    """
    Article model that represents a post. Will allow us to store posts in the database.
    """
    title = models.CharField(max_length=100)
    slug = models.SlugField(max_length=200, unique=True)
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    thumb = models.ImageField(default='default.png', blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, default=None, null=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)


    def __str__(self):
        return self.title

    def snippet(self):
        return self.body[:50] + '...'


class Comment(models.Model):
    """
    Comment model that represents a comment on a post.
    """
    post = models.ForeignKey(Article, on_delete=models.CASCADE, related_name='comments')
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    created = models.DateTimeField(default=timezone.now)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ['-created']

    def __str__(self):
        return f'Comment by {self.author.username} on {self.post.title}'

blog/articles/forms.py
from django import forms
from .models import Article, Comment

class CreateArticle(forms.ModelForm):
    class Meta:
        model = Article
        fields = ['title', 'body', 'thumb',]

class CommentForm(forms.ModelForm):
    post = forms.ModelChoiceField(queryset=Article.objects.all(), widget=forms.HiddenInput())

    class Meta:
        model = Comment
        fields = ['post', 'text']

blog/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout

def signup_view(request):
    if request.method == 'POST':
         form = UserCreationForm(request.POST)
         if form.is_valid():
             user = form.save()
             login(request, user)
             return redirect('articles:article_list')
    else:
        form = UserCreationForm()
    return render(request, 'accounts/signup.html', { 'form': form })


def login_view(request):

    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('articles:article_list')
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/login.html', {'form': form})


def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('articles:article_list')

blog/articles/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Article
from django.contrib.auth.decorators import login_required
from .forms import CommentForm

def article_list(request):
    articles = Article.objects.all().order_by('date')
    return render(request, 'articles/article_list.html', {'articles': articles})

@login_required(login_url="/accounts/login/")
def article_detail(request, slug):
    article = get_object_or_404(Article, slug=slug)
    comments = article.comments.filter(active=True)
    new_comment = None

    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            # new_comment.post = article
            new_comment.author = request.user
            new_comment.save()
            return redirect('articles:article_detail', slug=article.slug)
    else:
        comment_form = CommentForm(initial={'post': article.id})

    return render(request, 'articles/article_detail.html', {'article': article,
                                                            'comments': comments,
                                                            'new_comment': new_comment,
                                                            'comment_form': comment_form})

@login_required(login_url="/accounts/login/")
def article_create(request):
    if request.method == 'POST':
        form = forms.CreateArticle(request.POST, request.FILES)
        if form.is_valid():
            # save article to db
            instance = form.save(commit=False)
            instance.author = request.user
            instance.save()
            return redirect('articles:article_list')
    else:
        form = forms.CreateArticle()
    return render(request, 'articles/article_create.html', { 'form': form })

blog/accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}
    <h1>Login</h1>
    <form class="site-form" action="{% url 'accounts:login' %}" method="post">
        {% csrf_token %}
        {{ form }}
        {% if request.GET.next %}
            <input type="hidden" name="next" value="{{ request.GET.next }}" />
        {% endif %}
        <input type="submit" value="Login">
    </form>
{% endblock %}

blog/accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block content %}
    <h1>Signup</h1>
    <form class="site-form" action="{% url 'accounts:signup' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Signup">
    </form>
{% endblock %}

blog/articles/templates/articles/article_create.html
{% extends 'base.html' %}

{% block content %}
    <div class="create-article">
        <h2>Create an Awesome New Article</h2>
        <form class="site-form" action="{% url 'articles:article_create' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form }}
            <input type="submit" value="Create">
        </form>
    </div>
{% endblock %}

blog/articles/templates/articles/article_detail.html
{% extends 'base.html' %}

{% block content %}
<div class="article-detail">
    <div class="article">
        <img src="{{ article.thumb.url }}" />
        <h2>{{ article.title }}</h2>
        <p>{{ article.body }}</p>
        <p>{{ article.date }}</p>
    </div>

    <div class="comments">
        <h2>Comments</h2>
        {% for comment in comments %}
        <div class="comment">
            <p>{{ comment.author }} said:</p>
            <p>{{ comment.text }}</p>
        </div>
        {% endfor %}

        {% if request.user.is_authenticated %}
        <h2>Add a comment</h2>
        <form method="post">
            {% csrf_token %}
            {{ comment_form.as_p }}
            <button type="submit">Submit</button>
        </form>
        {% else %}
        <p>You need to <a href="{% url 'login' %}">log in</a> to add a comment.</p>
        {% endif %}
    </div>
</div>
{% endblock %}

blog/articles/templates/articles/article_list.html
{% extends 'base.html' %}

{% block content %}
    <h1>Articles List</h1>
    <div class="articles">
        {% for article in articles %}
            <div class="article">
                <h2><a href="{% url 'articles:article_detail' article.slug %}">{{ article.title }}</a></h2>
                <p>{{ article.snippet }}</p>
                <p>{{ article.date }}</p>
                <p class="author">added by {{ article.author.username }}</p>
            </div>
        {% endfor %}
    </div>        
{% endblock %}

blog/articles/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Articles</title>
        <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    </head>
    <body>
        <header class="wrapper">
            <a href="{% url 'articles:home' %}">Home</a>
            <nav>
                <ul>
                    {% if user.is_authenticated %}
                    <li>
                        <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
                            {% csrf_token %}
                            <button type="submit">Logout</button>
                        </form>
                    </li>
                    <li><a href="{% url 'articles:article_create' %}" class="highlight">New Article</a></li>
                    {% else %}
                    <li><a href="{% url 'accounts:login' %}">Login</a></li>
                    <li><a href="{% url 'accounts:signup' %}">Signup</a></li>
                    {% endif %}
                </ul>
            </nav>
        </header>
        <div class="wrapper">
            {% block content %}
            {% endblock %}
        </div>
    </body>
    </html>